on: [push]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run sh
        run: sh try.sh
        env:
          ROOT_DIR: ${{github.workspace}}
